# This is a basic workflow to help you get started with Actions

name: 'Delete Converter 1'

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  copy:
    name: 'Delete Converter 1'
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
         
      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: '${{secrets.AZURE_CREDENTIALS}}'
      # Converter App wird gelöscht   
      - name: remove Converter from container apps
        uses: azure/CLI@v1
        with:
         inlineScript: |
          # This command assumes you have logged in with az login
          az containerapp delete -g providermock -n biproconverter1 --yes
      
