# This is a basic workflow that is manually triggered

name: Manual version select

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Person to greet'
        # Default value if no value is explicitly provided
        default: '1.9.51-26a87b8'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string
        
# This is a basic workflow to help you get started with Actions

jobs:
  copy:
    name: 'Select Converter 2'
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
         
      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: '${{secrets.AZURE_CREDENTIALS}}'
      # Converter App wird gelöscht   
      - name: Deploy Converter from container apps
        uses: azure/CLI@v1
        with:
         inlineScript: |
          # This command assumes you have logged in with az login
          az containerapp create -n biproconverter2 -g providermock \
          --image containerregistrybipro.azurecr.io/biproconnect-430-converter:${{ inputs.name }} --environment providermock-app-env \
          --ingress external --target-port 8081 \
          --registry-server ${{secrets.REGISTRY_SERVER}} --registry-username ${{secrets.REGISTRY_USERNAME}} --registry-password ${{secrets.REGISTRY_PASSWORD}} \
          --query properties.configuration.ingress.fqdn \
          --min-replicas 1 --max-replicas 1
