# This is a basic workflow to help you get started with Actions

name: 'Stop Converter'

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  copy:
    name: 'Stop Converter'
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
         
      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: '${{secrets.AZURE_CREDENTIALS}}'
      #soll den Converter stoppen   
      - name: Stop Converter
        uses: azure/CLI@v1
        with:
          inlineScript: |
            # Azure Login erfolgreich
            az containerapp revision deactivate -g providermock --revision biproconverter--w2i27k9
